# Generated by Django 5.2.12 on 2026-03-31 06:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Сана')),
                ('total_entered', models.IntegerField(default=0, verbose_name='Кирганлар сони')),
                ('total_exited', models.IntegerField(default=0, verbose_name='Чиққанлар сони')),
                ('peak_hour', models.IntegerField(blank=True, null=True, verbose_name='Энг кўп мижоз соати')),
                ('average_stay_time', models.FloatField(blank=True, null=True, verbose_name='Ўртача қолиш вақти (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мижозлар оқими',
                'verbose_name_plural': 'Мижозлар оқими',
                'db_table': 'customer_flows',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.Ш.')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Лавозими')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт серияси')),
                ('is_registered', models.BooleanField(default=True, verbose_name='Рўйхатдан ўтганми')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актив')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ишга кирган санаси')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ходим',
                'verbose_name_plural': 'Ходимлар',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.Ш.')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tax_inspector', 'Soliq inspektori'), ('analyst', 'Analitik'), ('business_owner', 'Tadbirkor')], default='analyst', max_length=50, verbose_name='Roll')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Фойдаланувчи',
                'verbose_name_plural': 'Фойдаланувчилар',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_encoding', models.TextField(verbose_name='Шифрланган юз маълумоти')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name="Rasm yo'li")),
                ('confidence', models.FloatField(default=0.0, verbose_name='Ишонч даражаси')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='core.employee', verbose_name='Ходим')),
            ],
            options={
                'verbose_name': 'Ходим юзи',
                'verbose_name_plural': 'Ходимлар юзлари',
                'db_table': 'employee_faces',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.CharField(max_length=500, verbose_name='Manzili')),
                ('location_type', models.CharField(choices=[('cafe', 'Kafe'), ('restaurant', 'Restoran'), ('tea_house', 'Choyxona'), ('hair_salon', 'Sartaroshxona'), ('car_wash', 'Avtoyuvish'), ('service_center', 'Xizmat koʻrsatish markazi'), ('household_service', 'Maishiy xizmat'), ('other', 'Boshqa')], max_length=50, verbose_name='Turi')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik (Lat)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik (Long)')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='STIR (ИНН)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локациялар',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='KKTIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkt_serial', models.CharField(max_length=100, verbose_name='ККТ серия рақами')),
                ('kkt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='ККТ рақами')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sinxronizatsiya')),
                ('total_receipts', models.IntegerField(default=0, verbose_name='Чекlar soni')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Umumiy summa')),
                ('sync_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('error', 'Xatolik')], default='pending', max_length=50, verbose_name='Ҳолат')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkt_integrations', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'ККТ интеграцияси',
                'verbose_name_plural': 'ККТ интеграциялари',
                'db_table': 'kkt_integrations',
            },
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('hour', models.IntegerField()),
                ('heatmap_data', models.JSONField()),
                ('max_intensity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Юклама харитаси',
                'db_table': 'heatmaps',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.location', verbose_name='Локация'),
        ),
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_at', models.DateTimeField(db_index=True, verbose_name='Кирган вақти')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='Чиққан вақти')),
                ('stay_duration', models.FloatField(blank=True, null=True, verbose_name='Қолиш давомийлиги (мин)')),
                ('track_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking ID')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Ходимми?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.customerflow', verbose_name='Оқим')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.employee', verbose_name='Ходим')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_visits', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Мижоз ташрифи',
                'verbose_name_plural': 'Мижоз ташрифлари',
                'db_table': 'customer_visits',
            },
        ),
        migrations.AddField(
            model_name='customerflow',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_flows', to='core.location', verbose_name='Локация'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kamera nomi')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP manzil')),
                ('port', models.IntegerField(default=80, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Login')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parol')),
                ('onvif_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='ONVIF URL')),
                ('camera_type', models.CharField(choices=[('entrance', 'Kirish'), ('exit', 'Chiqish'), ('internal', 'Ichki')], default='entrance', max_length=50, verbose_name='Kamera turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi')),
                ('stream_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='RTSP/Stream URL')),
                ('resolution', models.CharField(default='1920x1080', max_length=50, verbose_name='Ruxsat (Resolution)')),
                ('fps', models.IntegerField(default=30, verbose_name='FPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камералар',
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Сана')),
                ('real_customers', models.IntegerField(default=0, verbose_name='Реал мижозлар')),
                ('reported_revenue', models.FloatField(default=0.0, verbose_name='Хисоботдаги тушум')),
                ('estimated_revenue', models.FloatField(default=0.0, verbose_name='Тахминий тушум')),
                ('average_check', models.FloatField(default=0.0, verbose_name='Ўртача чек')),
                ('discrepancy', models.FloatField(default=0.0, verbose_name='Тафовут')),
                ('discrepancy_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитикалар',
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=50)),
                ('factors', models.JSONField(blank=True, null=True)),
                ('unregistered_employees', models.IntegerField(default=0)),
                ('revenue_discrepancy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Риск баҳоси',
                'db_table': 'risk_scores',
            },
        ),
        migrations.CreateModel(
            name='TaxIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=50, verbose_name='STIR (ИНН) / Soliq ID')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sinxronizatsiya')),
                ('reported_revenue', models.FloatField(default=0.0, verbose_name='Ҳисоботдаги тушум')),
                ('tax_paid', models.FloatField(default=0.0, verbose_name='Тўланган солиқ')),
                ('sync_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('error', 'Xatolik')], default='pending', max_length=50, verbose_name='Ҳолат')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_integrations', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Солиқ интеграцияси',
                'verbose_name_plural': 'Солиқ интеграциялари',
                'db_table': 'tax_integrations',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateTimeField(verbose_name='Келиш вақти')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Кетиш вақti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core.employee', verbose_name='Ходим')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Иш журнали',
                'verbose_name_plural': 'Иш журналлари',
                'db_table': 'work_logs',
            },
        ),
    ]
