# Generated by Django 5.2.11 on 2026-04-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tganmi"),
        ),
    ]
