# Generated by Django on manually created with required fields from TZ

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='INN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_embedding',
            field=models.TextField(blank=True, null=True, verbose_name='Yuz embedding'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Солиқчи тасдиғи'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('fired', 'Ishdan bo‘шatilgan'), ('candidate_by_ai', 'AI tomonidan nomzod')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
