# Generated by Django 5.2.12 on 2026-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Рўйхатдан ўтганми'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('fired', 'Ishdan bo‘shatilgan'), ('candidate_by_ai', 'AI tomonidan nomzod')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
