# Generated by Django 5.2.12 on 2026-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tax_inspector', 'Soliq inspektori'), ('analyst', 'Analitik'), ('business_owner', 'Biznes egasi'), ('cafe_manager', 'Cafe menejer'), ('waiter', 'Ofitsiant'), ('kitchen', 'Oshpaz')], default='analyst', max_length=50, verbose_name='Roll'),
        ),
    ]
