# Generated by Django 5.2.12 on 2026-04-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_kitchen_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kilogramm'), ('g', 'Gramm'), ('l', 'Litr'), ('ml', 'Millilitr'), ('paket', 'Paket')], default='dona', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.location')),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
    ]
