# Generated by Django 5.2.12 on 2026-04-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=64, verbose_name='Yuz signaturasi')),
                ('date_str', models.CharField(db_index=True, max_length=10, verbose_name='Sana (YYYY-MM-DD)')),
                ('first_seen', models.DateTimeField(verbose_name="Birinchi ko'ringan vaqt")),
                ('last_seen', models.DateTimeField(verbose_name="Oxirgi ko'ringan vaqt")),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name="Ko'ringan marta")),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_customers', to='core.location', verbose_name='Lokatsiya')),
            ],
            options={
                'verbose_name': 'Kuzatilgan mijoz',
                'verbose_name_plural': 'Kuzatilgan mijozlar',
                'db_table': 'tracked_customers',
                'unique_together': {('signature', 'location', 'date_str')},
            },
        ),
    ]
