# Generated by Django 5.2.17 on 2026-09-03 07:55

import django.db.models.deletion
import src.core.models.customer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.CharField(default=src.core.models.customer.make_visitor_id, editable=False, max_length=20, unique=True, verbose_name='Visitor ID')),
                ('entered_at', models.DateTimeField(db_index=True, verbose_name='Kirish vaqti')),
                ('exited_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Chiqish vaqti')),
                ('last_seen_at', models.DateTimeField(verbose_name="Oxirgi ko'rilgan vaqt")),
                ('stay_duration', models.FloatField(blank=True, null=True, verbose_name='Davomiyligi (minut)')),
                ('status', models.CharField(choices=[('inside', 'Ichkarida'), ('completed', 'Chiqib ketgan')], default='inside', max_length=12)),
                ('is_long_stay', models.BooleanField(default=False, verbose_name='Uzoq qolgan')),
                ('face_embedding', models.TextField(blank=True, default='', verbose_name='Shifrlangan yuz vektori')),
                ('entry_image_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Kirish rasmi')),
                ('exit_image_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Chiqish rasmi')),
                ('biometric_purged_at', models.DateTimeField(blank=True, null=True, verbose_name="Biometrik ma'lumot o'chirilgan vaqt")),
                ('entry_camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_sessions', to='core.camera', verbose_name='Kirish kamerasi')),
                ('exit_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_sessions', to='core.camera', verbose_name='Chiqish kamerasi')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to='core.location', verbose_name='Lokatsiya')),
            ],
            options={
                'verbose_name': 'Mijoz tashrifi',
                'verbose_name_plural': 'Mijoz tashriflari',
                'db_table': 'visitor_sessions',
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['location', 'status', 'entered_at'], name='visitor_ses_locatio_ba024d_idx')],
            },
        ),
    ]
