# Generated by Django 5.2.17 on 2026-09-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visitorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsession',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_sessions', to='core.employee', verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Xodimmi'),
        ),
    ]
