# Generated by Django 5.2.17 on 2026-09-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_internal_camera_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.FloatField()),
                ('face_embedding', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('registered', "Ro'yxatdan o'tgan")], default='pending', max_length=12)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_employee_alerts', to='core.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_employees', to='core.location')),
                ('visitor_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='potential_employee', to='core.visitorsession')),
            ],
            options={
                'db_table': 'potential_employees',
                'ordering': ['-detected_at'],
            },
        ),
    ]
