# Generated by Django 5.2.17 on 2026-09-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_potentialemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Kirdi'), ('exit', 'Chiqdi')], max_length=8)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
                ('visitor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.visitorsession')),
            ],
            options={
                'db_table': 'visitor_events',
                'ordering': ['occurred_at'],
            },
        ),
    ]
