from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('core', '0020_taxintegration_manual_reports')]
    operations = [
        migrations.CreateModel(name='AuditLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('action', models.CharField(choices=[('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('restore', 'Qaytarish'), ('merge', 'Birlashtirish')], max_length=16)), ('entity_type', models.CharField(max_length=64)), ('entity_id', models.CharField(max_length=64)), ('summary', models.CharField(max_length=500)), ('before_data', models.JSONField(blank=True, default=dict)), ('after_data', models.JSONField(blank=True, default=dict)), ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)), ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.location'))], options={'db_table': 'audit_logs', 'ordering': ['-created_at']}),
        migrations.CreateModel(name='Notification', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('level', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('error', 'Muhim')], default='info', max_length=10)), ('title', models.CharField(max_length=255)), ('message', models.TextField()), ('is_read', models.BooleanField(default=False)), ('dedupe_key', models.CharField(max_length=255, unique=True)), ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.location')), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL))], options={'db_table': 'notifications', 'ordering': ['-created_at']}),
    ]
