# Generated by Codex for anonymous person-detection monitoring.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0022_nvr_gateway")]

    operations = [
        migrations.AddField(
            model_name="visitorsession",
            name="is_anonymous",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Yuzi aniqlanmagan anonim tashrif"),
        ),
    ]
