# Generated by Codex for auditable manual checkout records.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0023_visitorsession_is_anonymous")]

    operations = [
        migrations.AddField(
            model_name="visitorevent",
            name="is_manual",
            field=models.BooleanField(default=False, verbose_name="Admin qo‘lda qayd qilgan"),
        ),
    ]
