# Generated by Codex for anonymous person appearance snapshots.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0024_visitorevent_is_manual")]

    operations = [
        migrations.AddField(model_name="visitorsession", name="entry_body_image_path", field=models.CharField(blank=True, default="", max_length=500, verbose_name="Kirishdagi tashqi ko‘rinish")),
        migrations.AddField(model_name="visitorsession", name="exit_body_image_path", field=models.CharField(blank=True, default="", max_length=500, verbose_name="Chiqishdagi tashqi ko‘rinish")),
    ]
