# Generated by Django 5.2.17 on 2026-09-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_employee_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='Nofaol holat', max_length=255)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='core.camera')),
            ],
            options={
                'db_table': 'camera_downtimes',
                'ordering': ['-started_at'],
            },
        ),
    ]
