# Generated by Django 5.2.17 on 2026-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cameradowntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jshshir',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='JSHSHIR'),
        ),
    ]
