# Generated by Django 5.2.17 on 2026-09-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_employee_jshshir'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(default='rect', max_length=20),
        ),
        migrations.CreateModel(
            name='CafeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('width', models.PositiveIntegerField(default=900)),
                ('height', models.PositiveIntegerField(default=560)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_rooms', to='core.location')),
            ],
            options={
                'db_table': 'cafe_rooms',
                'ordering': ['name'],
                'unique_together': {('location', 'name')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='core.caferoom'),
        ),
    ]
