# Generated by Django 5.2.17 on 2026-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_table_position_x_table_position_y_table_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
