# Generated by Django 5.2.17 on 2026-09-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_table_height_table_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='caferoom',
            name='position_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='caferoom',
            name='position_y',
            field=models.IntegerField(default=20),
        ),
    ]
